#pragma once

#include <cstdint>
#include <functional>
#include <memory>
#include <vector>

#include <cortex/tiny_fiber/tiny_fiber.hpp>

#include "engine/event.h"
#include "lang/value.h"

namespace engine {

namespace tf = cortex::tiny_fiber;

// Manages Cortex fibers for async request handling in the simulation.
// Each request handler runs in its own fiber. Cross-component calls
// yield the fiber to simulate latency and allow other fibers to run.
class FiberRuntime {
public:
    FiberRuntime();
    ~FiberRuntime();
    FiberRuntime(FiberRuntime&&) noexcept;
    FiberRuntime& operator=(FiberRuntime&&) noexcept;

    // Spawn a fiber for a request handler.
    void SpawnHandler(std::function<void()> handler);

    // Run all spawned fibers to completion (blocking).
    // Fibers may yield internally to simulate latency.
    void RunAll();

    // Step one fiber quantum. Returns true if more work remains.
    bool Step();

    // Check if any fibers are still running
    [[nodiscard]] bool HasActiveFibers() const;

    // Collect events generated by fibers
    std::vector<Event> TakeGeneratedEvents();

    // Push an event from within a handler fiber
    void EmitEvent(Event event);

    // Get next unique request ID
    uint64_t NextRequestId();

    // Reset all state
    void Reset();

private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

}  // namespace engine
